In [3]:
# Local authority files
# LA-coords.csv
# LA-population.csv

import csv
import pandas as pd
import numpy as np

df_coords = pd.read_csv("LA-coords.csv")
df_population = pd.read_csv("LA-population.csv")

In [5]:
df_coords

          Code                  Name  Longitude   Latitude
0    E06000001            Hartlepool  -1.270174  54.676132
1    E06000002         Middlesbrough  -1.210998  54.544679
2    E06000003  Redcar and Cleveland  -1.006565  54.567520
3    E06000004      Stockton-on-Tees  -1.306646  54.556876
4    E06000005            Darlington  -1.568356  54.535345
..         ...                   ...        ...        ...
356  W06000020               Torfaen  -3.051019  51.698361
357  W06000021         Monmouthshire  -2.902806  51.778278
358  W06000022               Newport  -2.897690  51.582311
359  W06000023                 Powys  -3.435318  52.348639
360  W06000024        Merthyr Tydfil  -3.364252  51.748409

[361 rows x 4 columns]

In [7]:
df_population

          Code                     Name  Population2024
0    E06000047            County Durham          538011
1    E06000005               Darlington          112489
2    E06000001               Hartlepool           98180
3    E06000002            Middlesbrough          156161
4    E06000057           Northumberland          331420
..         ...                      ...             ...
356  N09000007  Lisburn and Castlereagh          151669
357  N09000008      Mid and East Antrim          139913
358  N09000009               Mid Ulster          152718
359  N09000010   Newry, Mourne and Down          183115
360  N09000011      Ards and North Down          165415

[361 rows x 3 columns]

In [17]:
df = pd.merge(df_coords, df_population, left_on='Code', right_on='Code', how='left')
df = df.drop(columns=['Name_y'])
df = df.rename(columns={"Name_x": "Name"})

In [19]:
df

          Code                  Name  Longitude   Latitude  Population2024
0    E06000001            Hartlepool  -1.270174  54.676132         98180.0
1    E06000002         Middlesbrough  -1.210998  54.544679        156161.0
2    E06000003  Redcar and Cleveland  -1.006565  54.567520        139228.0
3    E06000004      Stockton-on-Tees  -1.306646  54.556876        206800.0
4    E06000005            Darlington  -1.568356  54.535345        112489.0
..         ...                   ...        ...        ...             ...
356  W06000020               Torfaen  -3.051019  51.698361         94119.0
357  W06000021         Monmouthshire  -2.902806  51.778278         94930.0
358  W06000022               Newport  -2.897690  51.582311        167899.0
359  W06000023                 Powys  -3.435318  52.348639        135059.0
360  W06000024        Merthyr Tydfil  -3.364252  51.748409         58972.0

[361 rows x 5 columns]

In [21]:
df.to_csv("LA.csv")

In [5]:
# LSOA files (England + Wales)
# LSOA-coords.csv
# LSOA-population.csv
import csv
import pandas as pd
import numpy as np

df_lsoa_coords = pd.read_csv("LSOA-coords.csv")
df_lsoa_population = pd.read_csv("LSOA-population.csv")

In [7]:
df_lsoa_coords

,FID,LSOA21CD,LSOA21NM,LSOA21NMW,BNG_E,BNG_N,LAT,LONG,Shape__Area,Shape__Length,GlobalID
0,1,E01000001,City of London 001A,,532123,181632,51.51817,-0.097150,1.577948e+05,1685.391557,3478c558-3297-4e2b-979e-e29dd9ff3bf5
1,2,E01000002,City of London 001B,,532480,181715,51.51883,-0.091970,1.648821e+05,1804.827316,f2072109-b1ae-426c-b166-083cc32f1789
2,3,E01000003,City of London 001C,,532239,182033,51.52174,-0.095330,4.221605e+04,909.253080,a9009c33-9b6b-4230-ba62-fc3264806de4
3,4,E01000005,City of London 001E,,533581,181283,51.51469,-0.076280,2.127007e+05,2028.716721,86aee0aa-079f-4f92-8f9d-5773824f4945
4,5,E01000006,Barking and Dagenham 016A,,544994,184274,51.53875,0.089317,1.305512e+05,1716.731235,c33f1f5b-6b15-47a1-b046-b6a148a9f6d3
...,...,...,...,...,...,...,...,...,...,...,...
35667,35668,W01002036,Vale of Glamorgan 005G,Bro Morgannwg 005G,317939,172435,51.44494,-3.182180,4.411147e+05,2800.544728,f79ed9c6-8220-49d9-9a69-e80e9f0007cb
35668,35669,W01002037,Vale of Glamorgan 005H,Bro Morgannwg 005H,318527,172406,51.44476,-3.173710,2.321998e+05,2088.259479,fdd8e9dc-8504-4955-aa8d-e4cff563ed76
35669,35670,W01002038,Vale of Glamorgan 014G,Bro Morgannwg 014G,306491,167360,51.39754,-3.345520,3.496360e+06,10460.433787,7b56d7b1-48e6-4883-a46e-3bd00345bc8c
35670,35671,W01002039,Vale of Glamorgan 014H,Bro Morgannwg 014H,306564,166023,51.38553,-3.344120,5.819288e+05,3094.046530,36d00276-9970-4f4b-9322-5b89fdacf0c3
35671,35672,W01002040,Vale of Glamorgan 015F,Bro Morgannwg 015F,311423,167179,51.39670,-3.274600,6.898294e+05,4088.556787,85b0ef74-819a-42f1-b3e5-cfc570839651

In [9]:
df_lsoa_population

      LSOA 2021 Code       LSOA 2021 Name  Total
0          E01011949      Hartlepool 009A   1898
1          E01011950      Hartlepool 008A   1247
2          E01011951      Hartlepool 007A   1393
3          E01011952      Hartlepool 002A   1669
4          E01011953      Hartlepool 002B   2303
...              ...                  ...    ...
35667      W01001324  Merthyr Tydfil 003E   1848
35668      W01001898  Merthyr Tydfil 008F   1441
35669      W01001959  Merthyr Tydfil 005E   1528
35670      W01001960  Merthyr Tydfil 005F   1453
35671      W01001961  Merthyr Tydfil 006G   2356

[35672 rows x 3 columns]

In [25]:
df_lsoa = pd.merge(df_lsoa_coords, df_lsoa_population, left_on='LSOA21CD', right_on='LSOA 2021 Code', how='left')
df_lsoa = df_lsoa.drop(columns=['LSOA 2021 Name','LSOA 2021 Code','FID','LSOA21NMW','BNG_E','BNG_N','Shape__Area','Shape__Length','GlobalID'])
df_lsoa = df_lsoa.rename(columns={"Total": "Population"})

In [29]:
df_lsoa.to_csv('LSOA.csv')

In [69]:
# Local authority income files
# LA-coords.csv
# LA-income.csv

import csv
import pandas as pd
import numpy as np

df_coords = pd.read_csv("LA-coords.csv")
df_income = pd.read_csv("LA-income.csv")

In [71]:
df_coords

          Code                  Name  Longitude   Latitude
0    E06000001            Hartlepool  -1.270174  54.676132
1    E06000002         Middlesbrough  -1.210998  54.544679
2    E06000003  Redcar and Cleveland  -1.006565  54.567520
3    E06000004      Stockton-on-Tees  -1.306646  54.556876
4    E06000005            Darlington  -1.568356  54.535345
..         ...                   ...        ...        ...
356  W06000020               Torfaen  -3.051019  51.698361
357  W06000021         Monmouthshire  -2.902806  51.778278
358  W06000022               Newport  -2.897690  51.582311
359  W06000023                 Powys  -3.435318  52.348639
360  W06000024        Merthyr Tydfil  -3.364252  51.748409

[361 rows x 4 columns]

In [73]:
df_income

,Area Code,Area Name,Self-employment income: Number of individuals,Employment income: Number of individuals,Pension income: Number of individuals,Total income: Number of individuals,Total tax: Number of individuals,Total tax: Amount
0,E06000047,County Durham UA,18000,189000,90000,264000,264000,1140000000
1,E06000005,Darlington UA,4000,43000,18000,59000,59000,281000000
2,E06000001,Hartlepool UA,3000,34000,16000,46000,46000,195000000
3,E06000002,Middlesbrough UA,4000,50000,13000,62000,62000,270000000
4,E06000057,Northumberland UA,17000,124000,69000,182000,182000,1010000000
...,...,...,...,...,...,...,...,...
356,N09000006,Fermanagh and Omagh,8000,41000,14000,53000,53000,205000000
357,N09000007,Lisburn and Castlereagh,8000,58000,19000,75000,75000,471000000
358,N09000009,Mid Ulster,10000,57000,14000,71000,71000,306000000
359,N09000008,Mid and East Antrim,7000,55000,22000,73000,73000,311000000
360,N09000010,"Newry, Mourne and Down",13000,59000,20000,78000,78000,350000000

In [75]:
df_income = pd.merge(df_coords, df_income, left_on='Code', right_on='Area Code', how='left')
df_income = df_income.drop(columns=['Area Code','Area Name'])

In [77]:
df_income

,Code,Name,Longitude,Latitude,Self-employment income: Number of individuals,Employment income: Number of individuals,Pension income: Number of individuals,Total income: Number of individuals,Total tax: Number of individuals,Total tax: Amount
0,E06000001,Hartlepool,-1.270174,54.676132,3000.0,34000.0,16000.0,46000.0,46000.0,195000000.0
1,E06000002,Middlesbrough,-1.210998,54.544679,4000.0,50000.0,13000.0,62000.0,62000.0,270000000.0
2,E06000003,Redcar and Cleveland,-1.006565,54.567520,5000.0,45000.0,19000.0,62000.0,62000.0,262000000.0
3,E06000004,Stockton-on-Tees,-1.306646,54.556876,7000.0,77000.0,27000.0,99000.0,99000.0,520000000.0
4,E06000005,Darlington,-1.568356,54.535345,4000.0,43000.0,18000.0,59000.0,59000.0,281000000.0
...,...,...,...,...,...,...,...,...,...,...
356,W06000020,Torfaen,-3.051019,51.698361,3000.0,37000.0,13000.0,48000.0,48000.0,198000000.0
357,W06000021,Monmouthshire,-2.902806,51.778278,6000.0,38000.0,20000.0,55000.0,55000.0,387000000.0
358,W06000022,Newport,-2.897690,51.582311,6000.0,69000.0,23000.0,89000.0,89000.0,410000000.0
359,W06000023,Powys,-3.435318,52.348639,12000.0,42000.0,27000.0,67000.0,67000.0,301000000.0
360,W06000024,Merthyr Tydfil,-3.364252,51.748409,2000.0,22000.0,9000.0,30000.0,30000.0,113000000.0

In [79]:
df_income.to_csv('HMRC.csv')